#bootstrap docker-compose file
version: "3"

volumes:
  postgres-data:

services:
  zookeeper:
    image: "wurstmeister/zookeeper:3.4.6"
    container_name: Zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  broker:
    image: "wurstmeister/kafka:2.11-2.0.0"
    container_name: Kafka
    hostname: broker
    environment:
      KAFKA_BROKER_ID: 0
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: INTERNAL://:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://broker:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper

#  postgresql:
#    image: postgres:12-alpine
#    restart: always
#    hostname: db
#    environment:
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=postgres
#    ports:
#      - "5431:5432"
#    volumes:
#      - postgres-data:/var/lib/postgresql/data
